tradewinds/grains/urls.py
from django.conf.urls import url

from views import contacts, addFirm, index, viewFirm, addType, addAccount
from views import addPerson, addCompany, settings

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^addFirm$', addFirm, name='addFirm'),
    url(r'^contacts$', contacts, name='contacts'),
    url(r'^settings$', settings, name='settings'),
    url(r'^(?P<firm_id>[0-9]+)/$', viewFirm, name='viewFirm'),
    url(r'^addType$', addType, name='addType'),
    url(r'^addPerson$', addPerson, name='addPerson'),
    url(r'^addCompany$', addCompany, name='addCompany'),
    url(r'^addAccount/(?P<firm_id>[0-9]+)/$', addAccount, name='addAccount'),
]

tradewinds/tradewinds/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views

urlpatterns = [
    url(r'^$', views.index, name='main_index'),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',  {'next_page': '/login/'}),

    url(r'^grains/', include('grains.urls', namespace="grains")),
    url(r'^admin/', include(admin.site.urls)),
]

tradewinds/grains/models.py
from django.db import models
from django.contrib.auth.models import User

__doc__ ="""

    NOTES
        * By default, for every model, django creates
            id = models.AutoField(primary_key=True)

    TODO
        * datetime - We will add time related data fields shortly.
        *

"""

# Create your models here.
class Person(models.Model):

    firsName = models.CharField(max_length=60)
    lastName = models.CharField(max_length=60)
    phoneNum = models.CharField(max_length=15)
    website = models.URLField()
    email = models.EmailField()
    userId = models.ForeignKey(User)

    def __unicode__(self):
        return str(self.firsName + " " + self.lastName) 


class Company(models.Model):

    name = models.CharField(max_length=150)
    representative = models.ForeignKey(Person)
    phoneNum = models.CharField(max_length=15)
    website = models.URLField()
    email = models.EmailField()
    userId = models.ForeignKey(User)

    def __unicode__(self):
        return self.name
        

class Firm(models.Model):

    name = models.CharField(max_length=150)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        return self.name


class AccountType(models.Model):

    userId = models.ForeignKey(User)
    name = models.CharField(max_length=15)

    def __unicode__(self):
        return self.name


class Account(models.Model):

    firmId = models.ForeignKey(Firm)
    accountType = models.ForeignKey(AccountType)
    accountNumber = models.CharField(max_length=15)
    person = models.ForeignKey(Person, null=True)
    company = models.ForeignKey(Company, null=True)

    def __unicode__(self):
        return self.accountNumber


class TransactionType(models.Model):

    name = models.CharField(max_length=15)
    description = models.CharField(max_length=150)
    
    def __unicode__(self):
        return self.name


class Transaction(models.Model):

    firmId = models.CharField(max_length=150)
    account = models.ForeignKey(Account)
    amount = models.IntegerField()
    description = models.CharField(max_length=150)
    txType = models.ForeignKey(TransactionType)

tradewinds/grains/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.core.urlresolvers import reverse
from .models import User, Firm, AccountType, Person, Account, Company

@login_required
def index(request):
    firms = Firm.objects.all().filter(owner=request.user)
    return render_to_response('grains/index.html',
           {'firms': firms, 'user': request.user}, RequestContext(request))

@login_required
def settings(request):
    account_types = AccountType.objects.all().filter(userId=request.user)
    return render_to_response('grains/account_settings.html',
           {'user': request.user, 'types': account_types}, RequestContext(request))


@login_required
def addFirm(request):
    firm_name = request.POST['firm']
    firm_already_exists = Firm.objects.all().filter(owner=request.user,name=firm_name)
    if firm_already_exists or firm_name == "":
    	return HttpResponseRedirect(reverse('grains:index'))
    firm = Firm(name=firm_name, owner=request.user)
    firm.save()
    return HttpResponseRedirect(reverse('grains:index'))

@login_required
def contacts(request):
    account_types = AccountType.objects.all().filter(userId=request.user)
    persons = Person.objects.all().filter(userId=request.user)
    companies = Company.objects.all().filter(userId=request.user)
    print companies[0]
    return render_to_response('grains/add_contact.html',
                             {'user': request.user, 'types': account_types, 'persons': persons, 'companies': companies}, RequestContext(request))    

@login_required
def viewFirm(request, firm_id):
    firm_exists = Firm.objects.all().filter(id=firm_id,owner=request.user)
    if firm_exists:
        account_types = AccountType.objects.all().filter(userId=request.user)
        #company_accounts = Account.objects.all().filter(firmId=firm_id)
        accounts = Account.objects.all().filter(firmId=firm_id)
    	persons = Person.objects.all().filter(userId=request.user)
        companies = Company.objects.all().filter(userId=request.user)
        return render_to_response('grains/firm.html',
           {'persons': persons, 'companies': companies, 'accounts': accounts , 'firm_id': firm_exists[0].id, 'user': request.user, 'types': account_types}, RequestContext(request))
    return HttpResponseRedirect(reverse('grains:index'))

@login_required
def addType(request):
    type_name = request.POST['typename']
    type_already_exists = AccountType.objects.all().filter(name=type_name, userId=request.user)
    if not type_already_exists  or type_name == "":
        accountType = AccountType(name=type_name, userId=request.user)
        accountType.save()
    return HttpResponseRedirect(reverse('grains:index'))

@login_required
def addPerson(request):
    first_name = request.POST['firstname']
    last_name = request.POST['lastname']
    phone_num = request.POST['phonenum']
    website = request.POST['website']
    email = request.POST['email']
    person_exists = Person.objects.all().filter(phoneNum=phone_num,userId=request.user)
    if not person_exists:
        person = Person(firsName=first_name,lastName=last_name,phoneNum=phone_num,website=website,email=email,userId=request.user)
        person.save()
    return HttpResponseRedirect(reverse('grains:index'))    

@login_required
def addCompany(request):
    company_name = request.POST['companyname']
    first_name = request.POST['firstname']
    last_name = request.POST['lastname']
    phone_num = request.POST['phonenum']
    website = request.POST['website']
    email = request.POST['email']
    company_exists = Company.objects.all().filter(name=company_name,userId=request.user)
    if not company_exists:
        person = Person(firsName=first_name,lastName=last_name,phoneNum=phone_num,website=website,email=email,userId=request.user)
        person.save()
        company = Company(name=company_name,phoneNum=phone_num,website=website,email=email,representative=person,userId=request.user)
        company.save()
    return HttpResponseRedirect(reverse('grains:index'))  


@login_required
def addAccount(request, firm_id):
    account_num = request.POST['accountnum']
    type_id = request.POST['accounttype']
    person_id = request.POST['person']
    company_id = request.POST['company']

    firm_exists = Firm.objects.all().filter(id=firm_id,owner=request.user)
    if firm_exists:
        account_type = AccountType.objects.get(id=type_id,userId=request.user)
        if person_id == "":
            company = Company(id=company_id,userId=request.user)
            account_exists = Account(firmId=firm_exists[0],company=company)
            if not account_exists:
                account = Account(firmId=firm_exists[0],accountType=account_type,accountNumber=account_num,company=company)
                account.save()
        else:    
            person = Person(id=person_id,userId=request.user)
            account_exists = Account(firmId=firm_exists[0],person=person)
            if not account_exists:
                account = Account(firmId=firm_exists[0],accountType=account_type,accountNumber=account_num,person=person)
                account.save()
        return HttpResponseRedirect(reverse('grains:viewFirm', args=[firm_id]))
    return HttpResponseRedirect(reverse('grains:index'))

tradewinds/tradewinds/views.py
from django.shortcuts import render_to_response

def index(request):
    return render_to_response('index.html', {'title': 'TradeWinds - HomePage'})

tradewinds/grains/templates/grains/account_settings.html
{% extends "grains/layout.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <ul class='nav nav-tabs'>
    <li class='active'><a href='#type'>Account types</a></li>
  </ul>

    <div class='tab-content'>
	    <div class='tab-pane active' id='type'>
	    	</br>
	    	</br>
	    	<form action="{% url 'grains:addType'%}" method="post">
	        	{% csrf_token %}
	    		<div class="form-group">
				        <label for="typename">Type</label>
				        <input type="text" class="form-control" name="typename" id="typename" placeholder="Enter Type name" required>
				</div>
				<button type="submit" class="btn btn-default">Add Account Type</button>
	    	</form>
	        </br>
	        <h2 class="text text-primary">Account Types</h2>
	        {% if types %}
    			<ul class="list-group">
    			{% for type in types %}
        			<li class="list-group-item">{{ type.name }}</li>
    			{% endfor %}
    			</ul>
			{% else %}
				<p>No Account Types added</p>
			{% endif %}
	    </div>
	 </div>


<p>{{ firm }}</p>
    <script>
      $(function() {
        $('.nav-tabs a').click(function (e) {
          e.preventDefault();
          $(this).tab('show');
        });
      });
    </script>
{% endblock %}

tradewinds/grains/templates/grains/add_contact.html
{% extends "grains/layout.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <ul class='nav nav-tabs'>
    <li class='active'><a href='#person'>Person</a></li>
    <li><a href='#company'>Company</a></li>
  </ul>

    <div class='tab-content'>
	    <div class='tab-pane active' id='person'>
	        </br>
	    	</br>
		    	<form action="{% url 'grains:addPerson'%}" method="post"> 
		    		{% csrf_token %}             
					<div class="form-group">
				        <label for="firstname">First Name</label>
				        <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Enter First Name" required>
				    </div>
				    <div class="form-group">
				        <label for="lastname">Last Name</label>
				        <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Enter Last Name" required>
				    </div>
				    <div class="form-group">
				        <label for="phonenum">Phone Number</label>
				        <input type="text" class="form-control" name="phonenum" id="phonenum" placeholder="Enter Phone number" required>
				    </div>
				    <div class="form-group">
				        <label for="website">Website</label>
				        <input type="url" class="form-control" name="website" id="website" placeholder="http://url.com" required>
				    </div>
				    <div class="form-group">
				        <label for="email">Email</label>
				        <input type="email" class="form-control" name="email" id="email" placeholder="abc@xyz.com" required>
				    </div>
				    <button type="submit" class="btn btn-default">Add Person</button>
				</form>
			    </br>
		        <h2 class="text text-primary">Added Persons</h2>
		        {% if persons %}
	    			<ul class="list-group">
	    			{% for person in persons %}
	        			<li class="list-group-item">{{ person.firsName }} {{ person.lastName }}</li>
	    			{% endfor %}
	    			</ul>
				{% else %}
					<p>No Person added.</p>
				{% endif %}		
	    </div>
	    <div class='tab-pane fade' id='company'>
	        </br>
	    	</br>
		    	<form action="{% url 'grains:addCompany'%}" method="post"> 
		    		{% csrf_token %}
		    		<div class="form-group">
				        <label for="companyname">Company</label>
				        <input type="text" class="form-control" name="companyname" id="companyname" placeholder="Enter Company Name" required>
				    </div>             
					<div class="form-group">
				        <label for="firstname">First Name</label>
				        <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Enter First Name" required>
				    </div>
				    <div class="form-group">
				        <label for="lastname">Last Name</label>
				        <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Enter Last Name" required>
				    </div>
				    <div class="form-group">
				        <label for="phonenum">Phone Number</label>
				        <input type="text" class="form-control" name="phonenum" id="phonenum" placeholder="Enter Phone number" required>
				    </div>
				    <div class="form-group">
				        <label for="website">Website</label>
				        <input type="url" class="form-control" name="website" id="website" placeholder="http://url.com" required>
				    </div>
				    <div class="form-group">
				        <label for="email">Email</label>
				        <input type="email" class="form-control" name="email" id="email" placeholder="abc@xyz.com" required>
				    </div>
				    <button type="submit" class="btn btn-default">Add Company</button>
				</form>
			    </br>
		        <h2 class="text text-primary">Added Companies</h2>
		        {% if companies %}
	    			<ul class="list-group">
	    			{% for company in companies %}
	        			<li class="list-group-item">{{ company.name }}</li>
	    			{% endfor %}
	    			</ul>
				{% else %}
					<p>No Company added.</p>
				{% endif %}		
	    </div>
	 </div>


<p>{{ firm }}</p>
    <script>
      $(function() {
        $('.nav-tabs a').click(function (e) {
          e.preventDefault();
          $(this).tab('show');
        });
      });
    </script>
{% endblock %}

tradewinds/grains/templates/grains/firm.html
{% extends "grains/layout.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <ul class='nav nav-tabs'>
    <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Accounts
    <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="#person">Person</a></li>
      <li><a href="#company">Company</a></li>
    </ul>
  </li>
    <li class="active"><a href='#transaction'>Transactions</a></li>
  </ul>

    <div class='tab-content'>
	    <div class='tab-pane fade' id='person'>
	        </br>
	    	</br>
	    	{% if types %}
		    	<form action="{% url 'grains:addAccount' firm_id %}" method="post"> 
		    		{% csrf_token %}             
				    <div class="form-group">
				        <label for="accountnum">Enter Account number</label>
				        <input type="text" class="form-control" name="accountnum" id="accountnum" placeholder="Enter Account num" required>
				    </div>
				    <div class="form-group">
				  		<label for="person">Person:</label>
				  		<select class="form-control" name="person" id="person" required>
				    		{% for person in persons %}
								<option value="{{ person.id }}" SELECTED>{{ person.firsName }} {{ person.lastName }}</option>
							{% endfor %}
				  		</select>
				  	</div>
				  	<div class="form-group">
				  	<label for="accounttype">Account Type:</label>	
				  		<select class="form-control" name="accounttype" id="accounttype" required>
				    		{% for type in types %}
								<option value="{{ type.id }}" SELECTED>{{ type.name }}</option>
							{% endfor %}
				  		</select>
					</div>
					<input type="hidden" name="company" value="">
				    <button type="submit" class="btn btn-default">Add Account</button>
				</form>
			    {% else %}
			    	<p>No Account Types added. First add some Account Types.</p>
			    {% endif %}
			    </br>
		        <h2 class="text text-primary">My Accounts</h2>
		        {% if accounts %}
	    			<ul class="list-group">
	    			{% for account in accounts %}
	        			<li class="list-group-item">{{ account.person.firsName}} {{ account.person.lastName}} {{ account.company.name}} </li>
	    			{% endfor %}
	    			</ul>
				{% else %}
					<p>No Accounts added.</p>
				{% endif %}		
	    </div>
	    <div class='tab-pane fade' id='company'>
	        </br>
	    	</br>
	    	{% if types %}
		    	<form action="{% url 'grains:addAccount' firm_id %}" method="post"> 
		    		{% csrf_token %}             
				    <div class="form-group">
				        <label for="accountnum">Enter Account number</label>
				        <input type="text" class="form-control" name="accountnum" id="accountnum" value="" placeholder="Enter Account num" required>
				    </div>
				    <div class="form-group">
				  		<label for="company">Company:</label>
				  		<select class="form-control" name="company" id="company" required>
				    		{% for company in companies %}
								<option value="{{ company.id }}" SELECTED>{{ company.name }}</option>
							{% endfor %}
				  		</select>
				  	</div>
				    <div class="form-group">
				  		<label for="accounttype">Account Type:</label>
				  		<select class="form-control" name="accounttype" id="accounttype" required>
				    		{% for type in types %}
								<option value="{{ type.id }}" SELECTED>{{ type.name }}</option>
							{% endfor %}
				  		</select>
					</div>
					<input type="hidden" name="person" value="">
				    <button type="submit" class="btn btn-default">Add Account</button>
				</form>
			    {% else %}
			    	<p>No Account Types added. First add some Account Types.</p>
			    {% endif %}
			    </br>
		        <h2 class="text text-primary">My Accounts</h2>
		        {% if accounts %}
	    			<ul class="list-group">
	    			{% for account in accounts %}
	        			<li class="list-group-item">{{ account.person.firsName}} {{ account.person.lastName}} {{ account.company.name}} </li>
	    			{% endfor %}
	    			</ul>
				{% else %}
					<p>No Account added.</p>
				{% endif %}		
	    </div>
	    <div class='tab-pane active' id='transaction'>
	      <p>Transactions</p>
	    </div>
	 </div>


<p>{{ firm }}</p>
    <script>
      $(function() {
        $('.nav-tabs a').click(function (e) {
          e.preventDefault();
          $(this).tab('show');
        });
      });
    </script>
{% endblock %}

tradewinds/grains/templates/grains/form_example.html
{% extends "grains/layout.html" %}

{% block content %}
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
{% endblock %}

tradewinds/grains/templates/grains/index.html
{% extends "grains/layout.html" %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'grains:addFirm' %}" method="post">
{% csrf_token %}
    <div class="form-group">
	    <label for="firm">Firm</label>
	    <input type="text" class="form-control" name="firm" id="firm" placeholder="Enter Firm name" required/>
	</div>
	<button type="submit" class="btn btn-default">Add Firm</button>
</form>

<h2 class="text text-primary">My Firms</h2>
{% if firms %}
    <ul class="list-group">
    {% for firm in firms %}
        <li class="list-group-item"><a href="{% url 'grains:viewFirm' firm.id %}">{{ firm.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No firms are registered.</p>
{% endif %}
{% endblock %}

tradewinds/grains/templates/grains/layout.html
{% extends "base_layout.html" %}
{% block title %} {{ user.username }} - Logged in {% endblock %}
{% block full_page %}
<div class="container">
    <div class="row">
        <!-- Sidebar -->
        <div class="col-md-3">
            <p class="lead">Welcome {{ user.first_name }}</p>
            <div class="list-group">
                <a href="/grains" class="list-group-item active">Dashboard</a>
                <a href="{% url 'grains:settings' %}" class="list-group-item">Settings</a>
                <a href="{% url 'grains:contacts' %}" class="list-group-item">Contacts</a>
                <a href="/logout/" class="list-group-item">Logout</a>
            </div>
        </div>
        <!-- PageContent -->
        <div class="col-md-9">
            {% block content %}{% endblock %}
        </div>
        <!-- End PageContent -->
    </div>
</div>

{% endblock %}

tradewinds/templates/base_layout.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
   Using https://github.com/IronSummitMedia/startbootstrap-shop-item
   -->
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">
      <title>{% block title %}{% endblock %}</title>
      <!-- Bootstrap Core CSS -->
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom CSS -->
      <link href="{% static 'css/shop-item.css' %}" rel="stylesheet">
      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
      <script src="{% static 'js/jquery.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
   </head>
   <body>
      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
         <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="/">TradeWinds</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav">
                  <li>
                     <a href="/grains/">Grains</a>
                  </li>
                  <li>
                     <a href="#">Blog</a>
                  </li>
                  <li>
                     <a href="#">Contact</a>
                  </li>
                  <!-- <li>
                  {% if user.is_anonymous %}
                  <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
                  {% else %}
                  <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
                  {% endif %}
                  </li> -->
               </ul>
            </div>
            <!-- /.navbar-collapse -->
         </div>
         <!-- /.container -->
      </nav>
      <br />
      <br />
      <br />
      <br />
{% block full_page %}



{% endblock %}
      <!-- /.container -->
      <div class="container">
         <hr>
         <!-- Footer -->
         <footer>
            <div class="row">
               <div class="col-lg-12">
                  <p>Copyright &copy; TradeWinds 2016</p>
               </div>
            </div>
         </footer>
      </div>
      <!-- /.container -->
   </body>
</html>

tradewinds/templates/index.html
{% extends "base_layout.html" %}
{% block title %} {{ title }} {% endblock %}
{% block full_page %}
<div class="text text-center">
This is the main page
</div>
{% endblock %}